language: python
dist: bionic
compiler: gcc
python:
- "3.8"
services:
- xvfb
addons:
  apt:
    packages:
    - tcl-dev
    - tk-dev
    - fontconfig
    - libfontconfig1
    - libfontconfig1-dev
    - cmake
    - cmake-data
    - build-essential
install:
- python -m pip install nose scikit-build
script:
- python setup.py bdist_wheel
- python setup.py install
- rm -rf ./extrafont
- python -m nose
